services:
  redis:
    image: redis:7.2.6-alpine3.20
    restart: always
    ports:
      - 127.0.0.1:6379:6379
    command: >
      --requirepass temp
  postgres:
    image: postgres:17.2-alpine3.20
    restart: always
    volumes:
      - db:/var/lib/postgresql/data/
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: temp
      POSTGRES_USER: temp
      POSTGRES_PASSWORD: temp
volumes:
  db:
